app:
  datasources:
    sources:
      - name: postgres-primary
        type: jdbc
        url: jdbc:postgresql://postgres:5432/users_db
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
        primary: true
        priority: 100
        max-pool-size: 10
        min-pool-size: 2
        connection-timeout: 30000
        idle-timeout: 600000
        validation-query: SELECT 1
        properties:
          hibernate.hbm2ddl.auto: update
          hibernate.show_sql: true
          hibernate.format_sql: true

      - name: mongodb-secondary
        type: mongodb
        url: mongodb://mongodb:27017/users_db
        priority: 90
        properties:
          database: users_db
          auto-index-creation: true
          authentication-database: admin

spring:
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    com.aggregation.service: DEBUG
    org.springframework.data: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.jpa: DEBUG
    org.springframework.boot.actuate: DEBUG
