spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/users_db
      database: users_db
      auto-index-creation: true
      authentication-database: admin
  datasource:
    url: jdbc:postgresql://postgres:5432/users_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    com.aggregation.service: DEBUG
    org.springframework.data: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.jpa: DEBUG
    org.springframework.boot.actuate: DEBUG
