spring:
  application:
    name: Aggregation-Service
  main:
    allow-bean-definition-overriding: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false

data-sources:
  sources:
    - name: data-base-1
      type: jdbc
      strategy: h2
      url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1
      table: users
      username: sa
      password: 
      primary: true
      priority: 100
      mapping:
        id: id
        username: username
        name: first_name
        surname: last_name
        
    - name: data-base-2
      type: jdbc
      strategy: h2
      url: jdbc:h2:mem:db2;DB_CLOSE_DELAY=-1
      table: users
      username: sa
      password: 
      priority: 90
      mapping:
        id: id
        username: username
        name: first_name
        surname: last_name

    - name: mongodb-users
      type: mongodb
      url: mongodb://localhost:27017/users
      priority: 80

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    com.aggregation.service: DEBUG
    org.springframework.data: INFO
    org.hibernate: INFO
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.jpa: DEBUG
    org.springframework.boot.actuate: DEBUG